services:
  scrapper:
    image: scrapper
    container_name: scrapper
    restart: unless-stopped
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.routers.joplin.rule=Host(`scrapper.apis.fullstacklab.org`)
      - traefik.http.routers.joplin.tls.certresolver=letsencrypt
      - traefik.http.routers.joplin.entrypoints=https

networks:
  default:
    name: traefik
    external: true
